---
name: Run tests suite
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2

      - name: Install ZFS
        run: sudo apt-get install zfsutils-linux

      # needs root access to run zfs/zpool commands
      - name: Run go test
        run: sudo go test -race -v ./...

  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2

      - name: Install ZFS
        run: sudo apt-get install zfsutils-linux

      - name: Run go vet
        run: go vet ./...

  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29
          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
